version: '3.4'

services:
  wanttosell.api:
    image: ${DOCKER_REGISTRY-}wanttosellapi
    environment:
      - FILE_STORAGE_PATH=/app/data
    volumes:
      - ./host/directory:/app/data
    build:
      context: .
      dockerfile: WantToSell.Api/Dockerfile
    ports:
        - "5002:80" 
    depends_on:
        - wanttosell.redis
        - wanttosell.database  
    
  wanttosell.database:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: "WantToSellMSSQL"
    ports:
        - "1433:1433"
    volumes:
        - WTS-volume:/var/opt/mssql
    environment:
            SA_PASSWORD: "S3cur3P@ssW0rd!"
            ACCEPT_EULA: "Y"
  wanttosell.redis:
    restart: always
    image: "redis"
    container_name: "WantToSellRedis"
    ports:
        - "6379:6379"
volumes:
  WTS-volume: