version: '3.4'

services:
  wanttosell.api:
    image: ${DOCKER_REGISTRY-}wanttosellapi
    build:
      context: .
      dockerfile: WantToSell.Api/Dockerfile
    ports:
        - "5002:80" 
    depends_on:
        - wanttosell.database
    command: ["dotnet", "ef", "database update"]   
    
  wanttosell.database:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: "WantToSellMSSQL"
    ports:
        - "1433:1433"
    volumes:
        - WTS-volume:/var/opt/mssql
    environment:
            SA_PASSWORD: "S3cur3P@ssW0rd!"
            ACCEPT_EULA: "Y"
volumes:
  WTS-volume: